@BigChangeToDo_HostAddress = https://localhost:44319

GET {{BigChangeToDo_HostAddress}}/api/ToDoItems/
Accept: application/json

###
GET {{BigChangeToDo_HostAddress}}/api/ToDoItems/1
Accept: application/json